controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    hexapod_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
hexapod_arm_controller:
  ros__parameters:
    joints:
    - arm_L1_g1_roll_joint
    - arm_L1_g1_pitch_joint
    - arm_L1_g1_yaw_joint
    - arm_L1_g2_roll_joint
    - arm_L1_g2_pitch_joint
    - arm_L1_g2_yaw_joint
    - arm_L1_g3_roll_joint
    - arm_L1_g3_pitch_joint
    - arm_L1_g3_yaw_joint
    - arm_L1_g4_roll_joint
    - arm_L1_g4_pitch_joint
    - arm_L1_g4_yaw_joint
    - arm_L1_g5_roll_joint
    - arm_L1_g5_pitch_joint
    - arm_L1_g5_yaw_joint
    - arm_L2_g1_roll_joint
    - arm_L2_g1_pitch_joint
    - arm_L2_g1_yaw_joint
    - arm_L2_g2_roll_joint
    - arm_L2_g2_pitch_joint
    - arm_L2_g2_yaw_joint
    - arm_L2_g3_roll_joint
    - arm_L2_g3_pitch_joint
    - arm_L2_g3_yaw_joint
    - arm_L2_g4_roll_joint
    - arm_L2_g4_pitch_joint
    - arm_L2_g4_yaw_joint
    - arm_L2_g5_roll_joint
    - arm_L2_g5_pitch_joint
    - arm_L2_g5_yaw_joint
    - arm_L3_g1_roll_joint
    - arm_L3_g1_pitch_joint
    - arm_L3_g1_yaw_joint
    - arm_L3_g2_roll_joint
    - arm_L3_g2_pitch_joint
    - arm_L3_g2_yaw_joint
    - arm_L3_g3_roll_joint
    - arm_L3_g3_pitch_joint
    - arm_L3_g3_yaw_joint
    - arm_L3_g4_roll_joint
    - arm_L3_g4_pitch_joint
    - arm_L3_g4_yaw_joint
    - arm_L3_g5_roll_joint
    - arm_L3_g5_pitch_joint
    - arm_L3_g5_yaw_joint
    - arm_R1_g1_roll_joint
    - arm_R1_g1_pitch_joint
    - arm_R1_g1_yaw_joint
    - arm_R1_g2_roll_joint
    - arm_R1_g2_pitch_joint
    - arm_R1_g2_yaw_joint
    - arm_R1_g3_roll_joint
    - arm_R1_g3_pitch_joint
    - arm_R1_g3_yaw_joint
    - arm_R1_g4_roll_joint
    - arm_R1_g4_pitch_joint
    - arm_R1_g4_yaw_joint
    - arm_R1_g5_roll_joint
    - arm_R1_g5_pitch_joint
    - arm_R1_g5_yaw_joint
    - arm_R2_g1_roll_joint
    - arm_R2_g1_pitch_joint
    - arm_R2_g1_yaw_joint
    - arm_R2_g2_roll_joint
    - arm_R2_g2_pitch_joint
    - arm_R2_g2_yaw_joint
    - arm_R2_g3_roll_joint
    - arm_R2_g3_pitch_joint
    - arm_R2_g3_yaw_joint
    - arm_R2_g4_roll_joint
    - arm_R2_g4_pitch_joint
    - arm_R2_g4_yaw_joint
    - arm_R2_g5_roll_joint
    - arm_R2_g5_pitch_joint
    - arm_R2_g5_yaw_joint
    - arm_R3_g1_roll_joint
    - arm_R3_g1_pitch_joint
    - arm_R3_g1_yaw_joint
    - arm_R3_g2_roll_joint
    - arm_R3_g2_pitch_joint
    - arm_R3_g2_yaw_joint
    - arm_R3_g3_roll_joint
    - arm_R3_g3_pitch_joint
    - arm_R3_g3_yaw_joint
    - arm_R3_g4_roll_joint
    - arm_R3_g4_pitch_joint
    - arm_R3_g4_yaw_joint
    - arm_R3_g5_roll_joint
    - arm_R3_g5_pitch_joint
    - arm_R3_g5_yaw_joint
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
